[package]
name = "spel-authority"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
borsh = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
spel-framework = { git = "https://github.com/mmlado/spel.git", rev = "bbd887728d6c00accccbade5941256e8a43af6b6" }
