[package]
name = "spel-authority"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
borsh = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
spel-framework = { git = "https://github.com/mmlado/spel.git", rev = "56ea137d8203da9b860839de41fa4f965a21dec5" }
